In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

In [2]:
#LoadBatch

batch1 = pickle.load(open(r'C:\Users\satsin\batch1.pkl', 'rb'))
#remove batteries that do not reach 80% capacity
del batch1['b1c8']
del batch1['b1c10']
del batch1['b1c12']
del batch1['b1c13']
del batch1['b1c22']
numBat1 = len(batch1.keys())
batch2 = pickle.load(open(r'C:\Users\satsin\batch2.pkl','rb'))
# There are four cells from batch1 that carried into batch2, we'll remove the data from batch2
# and put it with the correct cell from batch1
batch2_keys = ['b2c7', 'b2c8', 'b2c9', 'b2c15', 'b2c16']
batch1_keys = ['b1c0', 'b1c1', 'b1c2', 'b1c3', 'b1c4']
add_len = [662, 981, 1060, 208, 482]
for i, bk in enumerate(batch1_keys):
    batch1[bk]['cycle_life'] = batch1[bk]['cycle_life'] + add_len[i]
    for j in batch1[bk]['summary'].keys():
        if j == 'cycle':
            batch1[bk]['summary'][j] = np.hstack((batch1[bk]['summary'][j], batch2[batch2_keys[i]]['summary'][j] + len(batch1[bk]['summary'][j])))
        else:
            batch1[bk]['summary'][j] = np.hstack((batch1[bk]['summary'][j], batch2[batch2_keys[i]]['summary'][j]))
    last_cycle = len(batch1[bk]['cycles'].keys())
    for j, jk in enumerate(batch2[batch2_keys[i]]['cycles'].keys()):
        batch1[bk]['cycles'][str(last_cycle + j)] = batch2[batch2_keys[i]]['cycles'][jk]
del batch2['b2c7']
del batch2['b2c8']
del batch2['b2c9']
del batch2['b2c15']
del batch2['b2c16']
numBat2 = len(batch2.keys())
batch3 = pickle.load(open(r'C:\Users\satsin\batch3.pkl','rb'))
# remove noisy channels from batch3
del batch3['b3c37']
del batch3['b3c2']
del batch3['b3c23']
del batch3['b3c32']
del batch3['b3c42']
del batch3['b3c43']
numBat3 = len(batch3.keys())
numBat = numBat1 + numBat2 + numBat3
bat_dict = {**batch1, **batch2, **batch3}
for i in bat_dict.keys():
    plt.plot(bat_dict[i]['summary']['cycle'], bat_dict[i]['summary']['QD'])
plt.xlabel('Cycle Number')
plt.ylabel('Discharge Capacity (Ah)')

#Batch_1 = pd.DataFrame(data=batch1)
#Batch_1.to_excel('summary1.xlsx')
#Batch_2 = pd.DataFrame(data=batch2)
#Batch_2.to_excel('summary2.xlsx')
#Batch_3 = pd.DataFrame(data=batch3)
#Batch_3.to_excel('summary3.xlsx')

test_ind = np.hstack((np.arange(0,(numBat1+numBat2),2),83))
train_ind = np.arange(1,(numBat1+numBat2-1),2)
secondary_test_ind = np.arange(numBat-numBat3,numBat)

MemoryError: 

In [86]:
test_ind

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 83])

In [87]:
train_ind

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81])

In [88]:
secondary_test_ind

array([ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,
        97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
       110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122,
       123])

In [89]:
df = pd.DataFrame(bat_dict)

In [90]:
df.head()

b1c0  \
cycle_life                                            [[1852.0]]   
charge_policy                                     3.6C(80%)-3.6C   
summary        {'IR': [0.0, 0.016742354, 0.016724309, 0.01668...   
cycles         {'0': {'I': [0, 0], 'Qc': [0, 0], 'Qd': [0, 0]...   

                                                            b1c1  \
cycle_life                                            [[2160.0]]   
charge_policy                                     3.6C(80%)-3.6C   
summary        {'IR': [0.0, 0.017038831, 0.017009802, 0.01692...   
cycles         {'0': {'I': [0, 0], 'Qc': [0, 0], 'Qd': [0, 0]...   

                                                            b1c2  \
cycle_life                                            [[2237.0]]   
charge_policy                                     3.6C(80%)-3.6C   
summary        {'IR': [0.0, 0.01686798, 0.016831938, 0.016718...   
cycles         {'0': {'I': [0, 0], 'Qc': [0, 0], 'Qd': [0, 0]...   

                                                            b1c3  \
cycle_life                                            [[1434.0]]   
charge_policy                                         4C(80%)-4C   
summary        {'IR': [0.0, 0.016369704, 0.016315572, 0.01632...   
cycles         {'0': {'I': [0, 0], 'Qc': [0, 0], 'Qd': [0, 0]...   

                                                            b1c4  \
cycle_life                                            [[1709.0]]   
charge_policy                                         4C(80%)-4C   
summary        {'IR': [0.0, 0.016787428, 0.016740341, 0.01673...   
cycles         {'0': {'I': [0, 0], 'Qc': [0, 0], 'Qd': [0, 0]...   

                                                            b1c5  \
cycle_life                                            [[1074.0]]   
charge_policy                                     4.4C(80%)-4.4C   
summary        {'IR': [0.0, 0.016437579, 0.016396422, 0.01636...   
cycles         {'0': {'I': [0, 0], 'Qc': [0, 0], 'Qd': [0, 0]...   

                                                            b1c6  \
cycle_life                                             [[636.0]]   
charge_policy                                     4.8C(80%)-4.8C   
summary        {'IR': [0.0, 0.017001977, 0.016977131, 0.01693...   
cycles         {'0': {'I': [0, 0], 'Qc': [0, 0], 'Qd': [0, 0]...   

                                                            b1c7  \
cycle_life                                             [[870.0]]   
charge_policy                                     4.8C(80%)-4.8C   
summary        {'IR': [0.0, 0.016311171, 0.016267659, 0.01623...   
cycles         {'0': {'I': [0, 0], 'Qc': [0, 0], 'Qd': [0, 0]...   

                                                            b1c9  \
cycle_life                                            [[1054.0]]   
charge_policy                                     5.4C(40%)-3.6C   
summary        {'IR': [0.0, 0.016978227, 0.01692898, 0.016933...   
cycles         {'0': {'I': [0, 0], 'Qc': [0, 0], 'Qd': [0, 0]...   

                                                           b1c11  ...  \
cycle_life                                             [[788.0]]  ...   
charge_policy                                       5.4C(50%)-3C  ...   
summary        {'IR': [0.0, 0.016575078, 0.016582273, 0.01658...  ...   
cycles         {'0': {'I': [0, 0], 'Qc': [0, 0], 'Qd': [0, 0]...  ...   

                                                           b3c33  \
cycle_life                                            [[1284.0]]   
charge_policy                            5C(67%)-4C-newstructure   
summary        {'IR': [0.015608473, 0.015511206, 0.015512635,...   
cycles         {'0': {'I': [0.4446896636363636, 0.74768759999...   

                                                           b3c34  \
cycle_life                                            [[1158.0]]   
charge_policy                          5.3C(54%)-4C-newstructure   
summary        {'IR': [0.01546871, 0.015438841, 0.015394062, ...   
cycles      

In [25]:
#Function to extract data cycle wise for each cell
#insert the cell no and cycle number to extract the data
#cell no varies from b1c0 to b3c43 and cycle number varies from 0 to 2300
def cycle(df):
    import pandas as pd
    cell_no = input("Enter the cell no.:")
    Index = int(input("Enter the index value:"))
    df1 = df.transpose()
    df2 = pd.DataFrame(df1['cycles'][cell_no])
    df3 = df2.transpose()
    df4 = pd.DataFrame()#df3['I'][Index],columns= ['I'])
    for i in list(df3):
        df5 = pd.DataFrame(df3[i][Index],columns = [i])
        df6 = df4.transpose()
        df7 = df6.append(df5.transpose())
        df4 = df7.transpose()
        df4.to_csv('C:\\Users\\satsin\\Desktop\\Battery life\\Cycle_'+str(cell_no)+'_'+str(Index)+'.csv')
    return(df4.shape)

In [ ]:
cycle(train)

In [ ]:
#function to extract all the data for different batches in different sheet cell wise for summary data
#Create one excel file in the shared location to save all the records and run the script in append mode,'a'
def summary(df):
    for i in list(df):
        cell = pd.DataFrame(df[i])
        cell_1 = cell.transpose()
        df3 = pd.DataFrame(cell_1['summary'][i])
        s_name = 'C:\\Users\\satsin\\Desktop\\Battery life\\summary_batch2.xlsx'
        with pd.ExcelWriter(s_name,engine="openpyxl",mode='a') as writer:
            d_name='Sheet_'+str(i)
            df3.to_excel(writer, sheet_name=d_name)
    return df3.shape

In [ ]:
summary(df)

In [ ]:
#function to extract all the data for different batches in different sheet cell wise for cycle data
#Create one excel file in the shared location to save all the records and run the script in append mode,'a'

def cycle_1(df):
    for i in list(df):
        cell = pd.DataFrame(df[i])
        cell_1 = cell.transpose()
        cell_2 = pd.DataFrame.from_dict({(j,k): cell_1['cycles'][j][k] 
                           for j in cell_1['cycles'].keys() 
                           for k in cell_1['cycles'][i].keys()},
                       orient='index')
        s_name = 'C:\\Users\\satsin\\Desktop\\Battery life\\extracted files\\Cycle_batch2.xlsx'
        with pd.ExcelWriter(s_name,engine="openpyxl",mode='a') as writer:
            d_name='Sheet_'+str(i)
            cell_2.to_excel(writer, sheet_name=d_name)
        
        #print(cell_3)
        
    return cell_2.shape

In [ ]:
cycle_1(df)